#!/bin/sh

status=$(cat /sys/class/power_supply/BAT*/status)
capacity=$(cat /sys/class/power_supply/BAT*/capacity)

if [ "$status" = "Discharging" ]; then
    if [ $capacity -gt 95 ]; then
        symbol=""
    elif [ $capacity -gt 90 ]; then
        symbol=""
    elif [ $capacity -gt 80 ]; then
        symbol=""
    elif [ $capacity -gt 70 ]; then
        symbol=""
    elif [ $capacity -gt 60 ]; then
        symbol=""
    elif [ $capacity -gt 50 ]; then
        symbol=""
    elif [ $capacity -gt 40 ]; then
        symbol=""
    elif [ $capacity -gt 30 ]; then
        symbol=""
    elif [ $capacity -gt 20 ]; then
        symbol=""
    elif [ $capacity -gt 10 ]; then
        symbol=""
    else
        symbol=""
	notify-send -h 'string:fgcolor:#ffffff' -h 'string:frcolor:#ff0000' -h 'string:bgcolor:#770000' \
		"Battery Extremly Low" "Plug in the AC adapter"
    fi
else
    if [ $capacity -gt 95 ]; then
        symbol=""
    elif [ $capacity -gt 90 ]; then
        symbol=""
    elif [ $capacity -gt 80 ]; then
        symbol=""
    elif [ $capacity -gt 70 ]; then
        symbol=""
    elif [ $capacity -gt 60 ]; then
        symbol=""
    elif [ $capacity -gt 50 ]; then
        symbol=""
    elif [ $capacity -gt 40 ]; then
        symbol=""
    elif [ $capacity -gt 30 ]; then
        symbol=""
    elif [ $capacity -gt 20 ]; then
        symbol=""
    elif [ $capacity -gt 10 ]; then
        symbol=""
    else
        symbol=""
    fi
fi

echo -e "${symbol} ${capacity}%"
