#!/bin/bash 

status=$(cat /sys/class/power_supply/BAT0/status)
capacity=$(cat /sys/class/power_supply/BAT0/capacity)

if [ "$status" = "Discharging" ]; then
    if [ $capacity -gt 95 ]; then
        symbol=""
    elif [ $capacity -gt 90 ]; then
        symbol=""
    elif [ $capacity -gt 80 ]; then
        symbol=""
    elif [ $capacity -gt 70 ]; then
        symbol=""
    elif [ $capacity -gt 60 ]; then
        symbol=""
    elif [ $capacity -gt 50 ]; then
        symbol=""
    elif [ $capacity -gt 40 ]; then
        symbol=""
    elif [ $capacity -gt 30 ]; then
        symbol=""
    elif [ $capacity -gt 20 ]; then
        symbol=""
    elif [ $capacity -gt 10 ]; then
        symbol=""
    else
        symbol=""
	notify-send -t 5000 -i $HOME/.dwmblocks/icons/lowbat.png "Battery Extremly Low" "Plug in the AC adapter"
    fi
else
    if [ $capacity -gt 95 ]; then
        symbol=""
    elif [ $capacity -gt 90 ]; then
        symbol=""
    elif [ $capacity -gt 80 ]; then
        symbol=""
    elif [ $capacity -gt 70 ]; then
        symbol=""
    elif [ $capacity -gt 60 ]; then
        symbol=""
    elif [ $capacity -gt 50 ]; then
        symbol=""
    elif [ $capacity -gt 40 ]; then
        symbol=""
    elif [ $capacity -gt 30 ]; then
        symbol=""
    elif [ $capacity -gt 20 ]; then
        symbol=""
    elif [ $capacity -gt 10 ]; then
        symbol=""
    else
        symbol=""
    fi
fi

echo -e "${symbol} ${capacity}%"
