#!/bin/sh

my_name=${0##*/}
my_dir=${0%/*}

[ -n ${TERM_EMULATOR} ] && EMULATOR=${TERM_EMULATOR} || EMULATOR=st

case $1 in
    1) # Left Click
		keyboard_layout --set; sigdwmblocks 2
        ;;
    6) # Shift + Left click
        ${EMULATOR} -e ${EDITOR} $my_dir/${my_name%_button}
        ;;
    7) # Shift + Right click
        ${EMULATOR} -e ${EDITOR} $my_dir/$my_name
        ;;
esac
