#!/bin/bash

# Note ~/.dwmblocks/current_lang needs to be created and initilised in the
# autostart.sh script

CURRENT_LANG_PATH="$HOME/.dwmblocks/current_lang"
CURRENT_LANG=$(cat $CURRENT_LANG_PATH)

case $CURRENT_LANG in
    "us")
        CURRENT_LANG="sr"
        ;;
    "sr")
        CURRENT_LANG="cp"
        ;;
    "cp")
        CURRENT_LANG="us"
        ;;
    *)
        exit
        ;;
esac
echo $CURRENT_LANG > $CURRENT_LANG_PATH
echo "  $CURRENT_LANG"
