#!/bin/bash

# Note ~/.dwmblocks/current_lang needs to be created and initilised in the
# autostart.sh script

CURRENT_LANG_PATH="$HOME/.dwmblocks/current_lang"
CURRENT_LANG=$(cat $CURRENT_LANG_PATH)

case $CURRENT_LANG in
    "us")
        CURRENT_LANG="rs"
		setxkbmap -layout rs -variant latin
        ;;
    "rs")
        CURRENT_LANG="pc"
		setxkbmap -layout rs
        ;;
    "pc")
        CURRENT_LANG="us"
		setxkbmap -layout us
        ;;
    *)
        exit
        ;;
esac
echo $CURRENT_LANG > $CURRENT_LANG_PATH
echo "  $CURRENT_LANG"
