#!/bin/bash 

volume="$(pamixer --get-volume)"

if [ "$volume" -gt "70" ]; then
	icon="墳"
elif [ "$volume" -lt "30" ]; then
	icon="奄"
else
	icon="奔"
fi

[ $(pamixer --get-mute) = true ] && icon="婢"

printf "$icon ${volume}%%"
