#!/bin/bash 

volume="$(pamixer --get-volume)"
[ $(pamixer --get-mute) = true ] && echo "  婢  "&& exit

if [ "$volume" -gt "70" ]; then
	icon="墳"
elif [ "$volume" -lt "30" ]; then
	icon="奄"
else
	icon="奔"
fi
printf "$icon ${volume}%%"